<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <!--If you are willing to use platform-specific APIs, use conditional compilation.
    See https://docs.avaloniaui.net/docs/guides/platforms/platform-specific-code/dotnet for more details.-->
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="favicon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="AvaloniaUI.DiagnosticsSupport">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Manitux\Manitux.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="helpers\osx-arm64\" />
    <Folder Include="helpers\osx-x64\" />
    <Folder Include="helpers\win-x64\" />
    <Folder Include="runtimes\linux-x64\native\" />
	  <Folder Include="runtimes\linux-arm64\native\" />
    <Folder Include="runtimes\osx-x64\native\" />
	  <Folder Include="runtimes\osx-arm64\native\" />
    <Folder Include="runtimes\win-x64\native\" />
  </ItemGroup>

<ItemGroup>
  <!-- Windows x64 -->
  <Content Include="runtimes\win-x64\native\*.dll" Condition="'$(RuntimeIdentifier)' == 'win-x64' or ('$(RuntimeIdentifier)' == '' and $([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows))))">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    <TargetPath>%(Filename)%(Extension)</TargetPath>
    <PublishState>Included</PublishState>
  </Content>

  <!-- Linux x64 -->
  <Content Include="runtimes\linux-x64\native\*.so*" Condition="'$(RuntimeIdentifier)' == 'linux-x64' or ('$(RuntimeIdentifier)' == '' and $([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux))))">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    <TargetPath>%(Filename)%(Extension)</TargetPath>
    <PublishState>Included</PublishState>
  </Content>
	
  <!-- Linux arm64 -->
  <Content Include="runtimes\linux-arm64\native\*.so*" Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    <TargetPath>%(Filename)%(Extension)</TargetPath>
    <PublishState>Included</PublishState>
  </Content>

  <!-- macOS x64  -->
  <Content Include="runtimes\osx-x64\native\*.dylib" Condition="'$(RuntimeIdentifier)' == 'osx-x64' or ('$(RuntimeIdentifier)' == '' and $([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX))))">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    <TargetPath>%(Filename)%(Extension)</TargetPath>
    <PublishState>Included</PublishState>
  </Content>

  <!-- macOS arm64  -->
  <Content Include="runtimes\osx-arm64\native\*.dylib" Condition="'$(RuntimeIdentifier)' == 'osx-arm64'">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    <TargetPath>%(Filename)%(Extension)</TargetPath>
    <PublishState>Included</PublishState>
  </Content>
</ItemGroup>

<ItemGroup>
<!-- Linux x64 -->
<None Include="helpers\linux-x64\tlsclientapi" Condition="$(RuntimeIdentifier.StartsWith('linux')) or ('$(RuntimeIdentifier)' == '' and $([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux))))">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    <Link>helpers\linux-x64\tlsclientapi</Link>
    <TargetPath>helpers\linux-x64\tlsclientapi</TargetPath>
  </None>

	<None Include="helpers\linux-x64\config.dist.yml" Condition="$(RuntimeIdentifier.StartsWith('linux')) or ('$(RuntimeIdentifier)' == '' and $([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux))))">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		<Link>helpers\linux-x64\config.dist.yml</Link>
		<TargetPath>helpers\linux-x64\config.dist.yml</TargetPath>
	</None>

  <None Include="helpers\linux-x64\ytdlp" Condition="$(RuntimeIdentifier.StartsWith('linux')) or ('$(RuntimeIdentifier)' == '' and $([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux))))">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    <Link>helpers\linux-x64\ytdlp</Link>
    <TargetPath>helpers\linux-x64\ytdlp</TargetPath>
  </None>

	
<!-- Windows x64 - for test  -->
<None Include="helpers\win-x64\tlsclientapi.exe" Condition="$(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and $([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows))))">
    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    <Link>helpers\win-x64\tlsclientapi.exe</Link>
    <TargetPath>helpers\win-x64\tlsclientapi.exe</TargetPath>
  </None>

	<None Include="helpers\win-x64\config.dist.yml" Condition="$(RuntimeIdentifier.StartsWith('win')) or ('$(RuntimeIdentifier)' == '' and $([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Windows))))">
		<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		<Link>helpers\win-x64\config.dist.yml</Link>
		<TargetPath>helpers\win-x64\config.dist.yml</TargetPath>
	</None>
</ItemGroup>

<Target Name="MakeHelperExecutable" AfterTargets="Publish">
  <Exec Condition="$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux))) and Exists('$(PublishDir)helpers/linux-x64/tlsclientapi')" Command="chmod +x $(PublishDir)helpers\linux-x64\tlsclientapi" />
  <Exec Condition="$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux))) and Exists('$(PublishDir)helpers/linux-x64/ytdlp')" Command="chmod +x $(PublishDir)helpers\linux-x64\ytdlp" />
  <!--<Exec Condition="$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::OSX)))" 
        Command="chmod +x $(PublishDir)tlsclientapi" />-->
</Target>
</Project>
